### ISSUE TITLE
Choose a new base color

### ISSUE THREAD

**Issue by grammaton** [EMUFest/emufest.github.io#16]
According with _style dep._ 2016 will be **RED**. 

@nenelenen will select the right **_dark_ RED**

**Comment by grammaton** [comment]
I opened a branch named **v2016style**
to use it @nenelenen need to do:

```
git pull
git checkout v2016style
```

**Comment by nenelenen** [comment]
#3c151c vinaccia
#361219
#301026 viola

**Comment by grammaton** [comment]
ok for `#301026`
